//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public lesson()
        {
            this.students = new HashSet<student>();
        }
    
        public int Id { get; set; }
        public int ResponsibleId { get; set; }
        public string NameLesson { get; set; }
        public int HourLesson { get; set; }
        public Nullable<System.DateTime> DatestartLesson { get; set; }
        public Nullable<System.DateTime> DateendLesson { get; set; }
    
        public virtual responsible responsible { get; set; }
        public virtual ICollection<student> students { get; set; }
    }
}
