//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsible
    {
        public responsible()
        {
            this.lessons = new HashSet<lesson>();
        }
    
        public int Id { get; set; }
        public string NameResponsible { get; set; }
        public string AdressResponsible { get; set; }
        public string EmailResponsible { get; set; }
        public string TelephoneResponsible { get; set; }
    
        public virtual ICollection<lesson> lessons { get; set; }
    }
}
