//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentmanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Id { get; set; }
        public int LessonId { get; set; }
        public string MatriculStudent { get; set; }
        public string NameStudent { get; set; }
        public string AdressStudent { get; set; }
        public string EmailStudent { get; set; }
        public string TelephoneStudent { get; set; }
        public int AgeStudent { get; set; }
    
        public virtual lesson lesson { get; set; }
    }
}
